const express = require('express');
const router = express.Router();
const multer = require('multer');
const crypto = require('crypto');
const PDFDocument = require('pdfkit');
const Milestone = require('../models/Milestone');
const auth = require('../middleware/auth');
const { uploadToImageKit } = require('../utils/imagekit');

const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 50 * 1024 * 1024 } });

// POST /api/files/upload
router.post('/upload', auth, upload.single('file'), async (req, res) => {
  try {
    if (!req.file) return res.status(400).json({ message: 'No file uploaded' });
    const buffer = req.file.buffer;
    const fileHash = crypto.createHash('sha256').update(buffer).digest('hex');
    const fileUrl = await uploadToImageKit(buffer, req.file.originalname, '/safelancer/files');
    res.json({ fileHash, fileUrl, fileName: req.file.originalname, message: 'File uploaded and hashed' });
  } catch (err) {
    res.status(500).json({ message: 'Server error', error: err.message });
  }
});

// POST /api/files/verify-hash — PUBLIC
router.post('/verify-hash', async (req, res) => {
  try {
    const { fileHash } = req.body;
    const milestone = await Milestone.findOne({ submissionFileHash: fileHash })
      .populate('client', 'name')
      .populate('freelancer', 'name')
      .populate('contract', 'hashId');

    if (!milestone) return res.json({ verified: false, message: 'Hash not found on platform' });

    res.json({
      verified: true,
      client: milestone.client?.name,
      freelancer: milestone.freelancer?.name,
      milestoneTitle: milestone.title,
      contractHashId: milestone.contract?.hashId,
      amount: milestone.amount,
      status: milestone.status,
      submittedAt: milestone.submittedAt,
      releasedAt: milestone.releasedAt,
      fileHash
    });
  } catch (err) {
    res.status(500).json({ message: 'Server error', error: err.message });
  }
});

// GET /api/files/certificate/:hash — PUBLIC, generates PDF
router.get('/certificate/:hash', async (req, res) => {
  try {
    const milestone = await Milestone.findOne({ submissionFileHash: req.params.hash })
      .populate('client', 'name')
      .populate('freelancer', 'name')
      .populate('contract', 'hashId');

    if (!milestone) return res.status(404).json({ message: 'Hash not found' });

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename="safelancer-certificate-${req.params.hash.substring(0, 8)}.pdf"`);

    const doc = new PDFDocument({ margin: 60 });
    doc.pipe(res);

    doc.fontSize(28).fillColor('#4F46E5').text('SafeLancer', { align: 'center' });
    doc.moveDown(0.3);
    doc.fontSize(16).fillColor('#1e293b').text('Proof of Delivery Certificate', { align: 'center' });
    doc.moveDown(1);
    doc.moveTo(60, doc.y).lineTo(550, doc.y).stroke('#4F46E5');
    doc.moveDown(1);
    doc.fontSize(12).fillColor('#334155');
    doc.text(`Client: ${milestone.client?.name || 'Unknown'}`);
    doc.text(`Freelancer: ${milestone.freelancer?.name || 'Unknown'}`);
    doc.text(`Milestone: ${milestone.title}`);
    doc.text(`Amount: ₹${milestone.amount}`);
    doc.text(`Status: ${milestone.status}`);
    doc.text(`Submitted: ${milestone.submittedAt?.toDateString() || 'N/A'}`);
    doc.text(`Released: ${milestone.releasedAt?.toDateString() || 'Pending'}`);
    doc.moveDown(1);
    doc.text('SHA-256 Hash:', { underline: true });
    doc.fontSize(9).text(req.params.hash, { wordBreak: 'break-all' });
    doc.moveDown(1);
    doc.fontSize(10).fillColor('#6b7280').text('This certificate was generated by SafeLancer. The SHA-256 hash above uniquely identifies the delivered file and proves it was not tampered with after submission.', { align: 'justify' });
    doc.end();
  } catch (err) {
    res.status(500).json({ message: 'Server error' });
  }
});

module.exports = router;
